import type { Portfolio, TagColors } from "../types/portfolio";

export const PORTFOLIO_INFO: Portfolio = {
  meta: {
    createdAt: new Date().toISOString(),
    locale: "en-US",
    url: "https://purvi.sehgaltech.com/",
    pdf: "/PURVI_SEHGAL_RESUME.pdf",
  },
  personal: {
    name: "Purvi Sehgal",
    title: "Senior Engineer — Full Stack (React & Node)",
    headline: "React · Redux · Node · Express · JS · SQL",
    avatar: "./profile.jpg",
    summary:
      "Senior Engineer with 5+ years of experience delivering enterprise-grade applications. Over the last 5 years I have focused on building production systems using React and Node JS — building responsive frontends and designing APIs.",
    contact: {
      email: "purvisehgal5@gmail.com",
      phone: "+91 8910 999 195",
      location: "Dabra, India",
      website: "https://purvi.sehgaltech.com/",
      socials: [
        {
          label: "LinkedIn",
          url: "https://www.linkedin.com/in/purvisehgal/",
          icon: "SiLinkedin",
        },
        {
          label: "GitHub",
          url: "https://github.com/purviprasad",
          icon: "SiGithub",
        },
        // {
        //   label: "Hugging Face",
        //   url: "link",
        //   icon: "SiHuggingface",
        // },
        // {
        //   label: "Kaggle",
        //   url: "link",
        //   icon: "SiKaggle",
        //   size: 32,
        // },
      ],
    },
  },
  highlights: [
    "Specialist Programmer L2 at Infosys (Apr 2023 – Present)",
    "Specialist Programmer at Infosys (Dec 2021 – Apr 2023)",
    "Digital Specialist Engineer at Infosys (Sep 2020 – Dec 2021)",
  ],
  skills: [
    {
      title: "Frontend",
      skills: [
        {
          name: "React",
          level: 95,
          icon: "SiReact",
          category: "frontend",
          years: 5,
          note: "Used in production since 2020",
        },
        {
          name: "Redux",
          level: 95,
          icon: "SiRedux",
          category: "frontend",
          years: 5,
          note: "Used in production since 2020",
        },
        {
          name: "JavaScript",
          level: 90,
          icon: "SiJavascript",
          category: "frontend",
          years: 6,
          note: "Used in production since 2019",
        },
        {
          name: "HTML5",
          level: 90,
          icon: "SiHtml5",
          category: "frontend",
          years: 6,
        },
        {
          name: "CSS3",
          level: 88,
          icon: "SiCss3",
          category: "frontend",
          years: 6,
        },
        {
          name: "TypeScript",
          level: 60,
          icon: "SiTypescript",
          category: "frontend",
          years: 3,
          note: "Used in production since 2021",
        },
        {
          name: "Redux Toolkit",
          level: 70,
          icon: "SiRedux",
          category: "frontend",
          years: 3,
          note: "Used in production since 2020",
        },
        {
          name: "Ant Design",
          level: 80,
          icon: "SiAntdesign",
          category: "frontend",
          years: 4,
          note: "Used in personal projects",
        },
        {
          name: "Tailwind CSS",
          level: 80,
          icon: "SiTailwindcss",
          category: "frontend",
          years: 2,
          note: "Used in personal projects",
        },
        {
          name: "Material-UI",
          level: 80,
          icon: "SiMui",
          category: "frontend",
          years: 2,
          note: "Used in personal projects",
        },
      ],
    },
    {
      title: "Backend",
      skills: [
        {
          name: "Node.js",
          level: 80,
          icon: "SiNodedotjs",
          category: "backend",
          years: 5,
          note: "Used in production since 2020",
        },
        {
          name: "Express.js",
          level: 75,
          icon: "SiExpress",
          category: "backend",
          years: 5,
          note: "Used in production since 2020",
        },
        {
          name: "Go Lang",
          level: 70,
          icon: "FaGolang",
          category: "backend",
          years: 2,
          note: "Used in production since 2024",
        },
        {
          name: "Python",
          level: 88,
          icon: "SiPython",
          category: "backend",
          years: 1,
        },
      ],
    },
    // {
    //   title: "AI & ML",
    //   skills: [
    //     {
    //       name: "NumPy",
    //       level: 85,
    //       icon: "SiNumpy",
    //       category: "data",
    //       years: 3,
    //       note: "Used in production since 2021",
    //     },
    //     {
    //       name: "Pandas",
    //       level: 85,
    //       icon: "SiPandas",
    //       category: "data",
    //       years: 3,
    //       note: "Used in production since 2021",
    //     },
    //     {
    //       name: "Scikit-learn",
    //       level: 80,
    //       icon: "SiScikitlearn",
    //       category: "data",
    //       years: 3,
    //       note: "Used in production since 2021",
    //     },
    //     {
    //       name: "TensorFlow",
    //       level: 75,
    //       icon: "SiTensorflow",
    //       category: "data",
    //       years: 2,
    //       note: "Used in production since 2022",
    //     },
    //     {
    //       name: "PyTorch",
    //       level: 75,
    //       icon: "SiPytorch",
    //       category: "data",
    //       years: 2,
    //       note: "Used in production since 2022",
    //     },
    //     {
    //       name: "RAG",
    //       level: 70,
    //       category: "data",
    //       years: 1,
    //       note: "Built POCs using LangChain and LlamaIndex",
    //     },
    //   ],
    // },
    // {
    //   title: "Infrastructure & DevOps",
    //   skills: [
    //     {
    //       name: "Terraform",
    //       level: 80,
    //       icon: "SiTerraform",
    //       category: "devops",
    //       years: 3,
    //       note: "Used in production since 2021",
    //     },
    //     {
    //       name: "Bicep",
    //       level: 70,
    //       category: "devops",
    //       years: 2,
    //       note: "Used in production since 2022",
    //     },
    //     {
    //       name: "AWS",
    //       level: 78,
    //       icon: "SiAmazonaws",
    //       category: "devops",
    //       years: 3,
    //       note: "Used in production since 2021",
    //     },
    //     {
    //       name: "Azure",
    //       level: 78,
    //       icon: "SiMicrosoftazure",
    //       category: "devops",
    //       years: 3,
    //       note: "Used in production since 2021",
    //     },
    //     {
    //       name: "Docker",
    //       level: 75,
    //       icon: "SiDocker",
    //       category: "devops",
    //       years: 3,
    //       note: "Used in production since 2021",
    //     },
    //     {
    //       name: "GitHub Actions",
    //       level: 75,
    //       icon: "SiGithubactions",
    //       category: "devops",
    //       years: 2,
    //       note: "Used in production since 2022",
    //     },
    //   ],
    // },
    {
      title: "Databases",
      skills: [
        {
          name: "PostgreSQL",
          level: 90,
          icon: "SiPostgresql",
          category: "database",
          years: 5,
          note: "Used in production since 2020",
        },
        {
          name: "MySQL",
          level: 78,
          icon: "SiMysql",
          category: "database",
          years: 5,
          note: "Used in production since 2020",
        },
        {
          name: "MongoDB",
          level: 78,
          icon: "SiMongodb",
          category: "database",
          years: 2,
          note: "Used in personal projects",
        },
      ],
    },
    {
      title: "Other Tools",
      skills: [
        {
          name: "Git",
          level: 90,
          icon: "SiGit",
          category: "tooling",
          years: 6,
          note: "Used in production since 2018",
        },
        {
          name: "GitHub",
          level: 88,
          icon: "SiGithub",
          category: "tooling",
          years: 6,
          note: "Used in production since 2018",
        },
        {
          name: "Postman",
          level: 90,
          icon: "SiPostman",
          category: "tooling",
          years: 6,
          note: "Used in production since 2018",
        },
        {
          name: "Splunk",
          level: 90,
          icon: "SiSplunk",
          category: "tooling",
          years: 5,
          note: "Used in production since 2020",
        },
        {
          name: "Miro",
          level: 90,
          icon: "SiMiro",
          category: "tooling",
          years: 3,
          note: "Used in production since 2023",
        },
        {
          name: "Jira",
          level: 90,
          icon: "SiJira",
          category: "tooling",
          years: 5,
          note: "Used in production since 2020",
        },
        {
          name: "Confluence",
          level: 90,
          icon: "SiConfluence",
          category: "tooling",
          years: 5,
          note: "Used in production since 2020",
        },
        {
          name: "VS Code",
          level: 95,
          icon: "VscVscode",
          category: "tooling",
          years: 6,
          note: "Used in production since 2019",
        },
        {
          name: "Jenkins",
          level: 80,
          icon: "SiJenkins",
          category: "tooling",
          years: 4,
          note: "Used in production since 2020",
        },
      ],
    },
  ],
  experience: [
    {
      id: "infy-SPL2-2023",
      title: "Specialist Programmer L2 - Apple Inc.",
      company: "Infosys Ltd.",
      location: "Remote",
      date: { start: "2023-04", present: true },
      //TODO
      summary:
        "",
      bullets: [
        "Led end-to-end delivery of a project from inception to production within a 4-member team.",
        "Optimized a high-memory data generation pipeline by re-architecting a Go-based solution to Node.js with delta filtering, cutting memory use by roughly half on representative workloads (e.g. 12 GB → 6 GB).",
        "Owned backend & frontend architecture, database design, and client collaboration; consistently recognized for efficient planning, optimized code, and strong stakeholder feedback.",
        "Mentor engineers, conduct design reviews, and improve code quality and observability.",
      ],
      tech: [
        "React",
        "Redux",
        "REST APIs",
        "Node",
        "Express",
        "Microservices",
        "TypeScript",
        "PostgreSQL",
        "AWS",
        "Ag-grid",
        "Cron",
        "Go Lang",
        "Jenkins",
        "Splunk",
        "Miro",
        "Postman",
        "GitHub",
        "VS Code",
      ],
    },
    {
      id: "infy-SPL1-2021",
      title: "Specialist Programmer L1 - Verizon Communications",
      company: "Infosys Ltd.",
      location: "Remote",
      date: { start: "2021-12", end: "2023-04" },
      summary:
        "",
      bullets: [
        "Independently built and delivered 2 POCs for Verizon Communications.",
        "Migrated a legacy codebase to Micro Frontend architecture using Module Federation, improving modularity and scalability.",
        "Developed and maintained high-quality MERN stack applications for Verizon, resulting in a 20% increase in user engagement.",
      ],
      tech: ["React", "Redux", "RTK", "Node", "Express", "Microservices", "Cron", "MySQL", "PostgreSQL", "Jenkins", "Splunk", "Postman", "GitHub", "VS Code"],
    },
    {
      id: "infy-dse-2020",
      title: "Digital Specialist Engineer - Verizon Communications",
      company: "Infosys Ltd.",
      location: "Remote",
      date: { start: "2020-09", end: "2021-12" },
      summary:
        "",
      bullets: [
        "Collaborated with cross-functional teams to gather requirements, provide technical expertise, and implement robust solutions.",
        "Played a key role in the successful and seamless delivery of the project in the Telecommunication domain.",
      ],
      tech: ["React", "Redux", "RTK", "Node", "Express", "Microservices", "TypeScript", "Cron"],
    },
  ],
  projects: [
    {
      id: "psui",
      title: "PSUI",
      fullForm: "Pro Style UI",
      packageName: "@sehgaltech/psui",
      tagline: "Headless. Themeable. Beautiful.",
      short:
        "A headless, themeable React component library built with Radix and Tailwind to help teams ship accessible interfaces faster.",
      description:
        "Pro Style UI is a scalable and customizable UI library built with Tailwind CSS v4, TypeScript, and React. It focuses on headless primitives, theme flexibility, accessibility, and a polished developer experience for building production-ready interfaces faster.",
      features: [
        "Tailwind CSS v4 with modern CSS-first configuration and @theme blocks",
        "TypeScript-first APIs for type safety and a strong developer experience",
        "Built with tsup for fast ESM and CJS package output",
        "Interactive documentation site powered by Vite",
        "Vitest and React Testing Library for component testing",
        "Tree-shakeable exports for smaller bundles",
        "Easy theme customization through CSS variables",
      ],
      tags: [
        "React",
        "TypeScript",
        "Tailwind CSS v4",
        "Radix UI",
        "Headless UI",
        "Component Library",
        "Vite",
        "Vitest",
        "tsup",
        "NPM",
      ],
      image: "https://media0.giphy.com/media/v1.Y2lkPTc5MGI3NjExN2h4b2djdm13d3Y2a3pjem45dWY4Y251cXdlaXk4NHNjZG9jZXQzOSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/qEMov1GrEwleBRXHdE/giphy.gif",
      domain: "UI Library",
      createdFor: "Personal Project",
      darkModeSupport: true,
      links: [
        {
          label: "Website",
          url: "https://psui.sehgaltech.com/",
          icon: "FaGlobe",
        },
        {
          label: "Docs",
          url: "https://psui.sehgaltech.com/docs/getstarted",
          icon: "FaBook",
        },
        {
          label: "NPM Package",
          url: "https://www.npmjs.com/package/@sehgaltech/psui",
          icon: "SiNpm",
        },
      ],
      isUnderDevelopment: true,
    },
    {
      id: "pigb",
      title: "PigB – Master Your Money with PigB",
      description:
        "Manage your finances with ease — track income, expenses, budgets, loans, and get AI-powered reports and insights, all in one beautiful dashboard.",
      tags: ["React", "Next.js", "TailwindCSS", "Ant Design", "Context API", "Recharts", "Framer Motion", "React Icons", "React Markdown", "MongoDB", "Node.js", "Express", "JWT", "Google OAuth 2.0", "Redis", "Finance"],
      image: "https://media1.giphy.com/media/v1.Y2lkPTc5MGI3NjExdWN6ZGV1ZjA2cGxibzVoYm9tN3Z5a2p4ZHEydzd1bWVnY2U5ZTEzbiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/AV8smlt6yfkUtwW39B/giphy.gif",
      // href: "https://pigb.sehgaltech.com/",
      domain: "Finance",
      createdFor: "Personal Project",
      darkModeSupport: true,
      credentials: {
        username: "test@test.com",
        password: "test"
      },
      links: [
        {
          label: "Live Site",
          url: "https://pigb.sehgaltech.com/",
          icon: "FaGlobe",
        },
      ],
      isUnderDevelopment: false,
    },
    {
      id: "finmate",
      title: "FinMate – Your One Stop Finance Buddy",
      description:
        "FinMate empowers users to track expenses, manage bills, plan and track savings, and gain insights into their finances. Built to address modern financial challenges with powerful tracking and visualization tools.",
      tags: ["React", "Ant Design", "Redux", "Webpack", "AntD Charts", "Syncfusion React Data Grid", "React Icons", "MySQL", "Node.js", "Express", "JWT", "Nodemailer", "Node Cron", "Finance"],
      image: "/trimmed-finmate-ezgif.com-video-to-gif-converter.gif",
      // href: "https://finmate.sehgaltech.com/",
      domain: "Finance",
      createdFor: "Microsoft GitHub Copilot Hackathon",
      credentials: {
        username: "demo",
        password: "test"
      },
      links: [
        {
          label: "Live Site",
          url: "https://finmate.sehgaltech.com/",
          icon: "FaGlobe",
        },
      ],
      isUnderDevelopment: false,
    },
    {
      id: "skr-payroll",
      title: "SKR (Sant Kanwar Ram Higher Secondary School)",
      description:
        "A centralized platform for administrators and HR personnel to handle automatic salary calculations, employee records, and payroll management. Simplifies complex tax and allowance calculations within the education sector. It simplifies the complex task of managing salary structures, allowances, deductions, and tax calculations, ensuring accuracy and compliance.",
      tags: ["React", "Ant Design", "Redux", "Webpack", "AntD Charts", "Syncfusion React Data Grid", "MySQL", "Node.js", "Express", "JWT", "Education"],
      image: "/trimmedskr-ezgif.com-video-to-gif-converter.gif",
      domain: "Education",
      createdFor: "Sant Kanwar Ram High School, Dabra",
      links: [
        // {
        //   label: "GitHub",
        //   url: "https://github.com/purviprasad/skr_frontend",
        //   icon: "FaGithub",
        // },
      ],
      isUnderDevelopment: false,
    }
  ],
  education: [
    {
      degree: "B.Tech in Computer Science Engineering",
      school: "Haldia Institute of Technology",
      date: "2016-2020",
    },
    {
      degree: "Higher Secondary",
      school: "Sri Chaitanya Engineering College",
      date: "2014-2016",
    },
    {
      degree: "High School",
      school: "Calcutta Public School",
      date: "2014",
    },
  ],
  certifications: [
    {
      name: "Frontend Developer (React) Certificate",
      issuer: "HackerRank",
      date: "2023",
      url: "https://www.hackerrank.com/certificates/5fd9534d0c13",
    },
    {
      name: "React (Basic) Certificate",
      issuer: "HackerRank",
      date: "2023",
      url: "https://www.hackerrank.com/certificates/b5083a2e8c38",
    },
    {
      name: "Introduction to Generative AI",
      issuer: "Google",
      date: "2023",
      url: "https://partner.cloudskillsboost.google/public_profiles/1f34fff7-e0ee-455a-8860-d0e6fb26301d/badges/5342557?utm_medium=social&utm_source=linkedin&utm_campaign=ql-social-share",
    },
    {
      name: "Introduction to Front-End Development",
      issuer: "Coursera",
      date: "2023",
      url: "https://www.coursera.org/account/accomplishments/verify/33VZVH3XB5WS",
    },
  ],
  awards: [
    {
      name: "RISE Insta Award",
      issuer: "Infosys Limited",
      date: "Dec 2025",
      associatedWith: "Infosys",
      description: "Purvi has consistently fulfilled the assigned task on time along with assisting other teams in debugging and resolving issues. Additionally she has actively contributed to the team's recruitment process.",
      url: "/certifications/INFOSYS_INSTA_DEC_2025.png"
    },
    {
      name: "RISE Gracias Award",
      issuer: "Infosys Limited",
      date: "Mar 2025",
      associatedWith: "Infosys",
      description: "Thank you for being the Tech Wizard who turns miracles into technology.",
      url: "/certifications/INFOSYS_GRACIAS_MAR_2025.png"
    },
    {
      name: "RISE Glory Award",
      issuer: "Verizon Communications",
      date: "Feb 2022",
      associatedWith: "Infosys",
    },
    {
      name: "RISE Insta Award",
      issuer: "Infosys Limited",
      date: "Jun 2021",
      associatedWith: "Infosys",
      description: "Thanks for all your hard work and dedication towards the Network Transparency ART. Appreciate all your hard work in implementing the KIRKE PI 8 user stories.",
      url: "/certifications/INFOSYS_INSTA_JUNE_2021.png"
    },
  ],
  extras: {
    languages: [{ name: "English", level: "Native" }],
    interests: ["dance", "music"],
  },
};

// ---------- SMALL HELPERS ----------
export const tagColors: TagColors = {
  React: "bg-blue-100 text-blue-800",
  CSS: "bg-teal-100 text-teal-800",
  CSS3: "bg-teal-100 text-teal-800",
  Tailwind: "bg-teal-100 text-teal-800",
  Stripe: "bg-purple-100 text-purple-800",
  "Design System": "bg-yellow-100 text-yellow-800",
  D3: "bg-amber-100 text-amber-800",
  Realtime: "bg-green-100 text-green-800",
  Storybook: "bg-pink-100 text-pink-800",
  "NPM Package": "bg-red-100 text-red-800",
  "Material-UI": "bg-indigo-100 text-indigo-800",
  Chatbot: "bg-violet-100 text-violet-800",
  OpenAI: "bg-gray-100 text-gray-800",
  "Hugging Face": "bg-orange-100 text-orange-800",
  Beginner: "bg-cyan-100 text-cyan-800",
  "Beginner Project": "bg-cyan-100 text-cyan-800",
  // Landing Zone Orchestrator tags
  FastAPI: "bg-teal-500 text-white",
  MongoDB: "bg-green-600 text-white",
  Terraform: "bg-purple-600 text-white",
  IaC: "bg-indigo-500 text-white",
  AWS: "bg-orange-500 text-white",
  Azure: "bg-blue-600 text-white",
  GCP: "bg-red-600 text-white",
  Algorithms: "bg-blue-500 text-blue-100",
  DSA: "bg-purple-300 text-purple-900",
  ML: "bg-blue-200 text-blue-800",
  AI: "bg-gray-200 text-gray-800",
  "AI & ML": "bg-amber-100 text-amber-900",
  Visualization: "bg-orange-100 text-purple-900",
  "Next.js": "bg-black text-white",
  "Full Stack": "bg-gradient-to-r from-blue-500 to-purple-600 text-white",
};
